package com.example.aggregator.domain.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/** 情報源マスタ（TBL-Sources / sources）。 */
@Entity
@Table(name = "sources")
public class SourceEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // GENERATED BY DEFAULT AS IDENTITY
    private Long id;

    @Column(name = "name", nullable = false)
    private String name;

    @Column(name = "url", nullable = false)
    private String url;

    @Column(name = "fetch_type", nullable = false)
    private FetchType fetchType;

    @Column(name = "is_active", nullable = false)
    private boolean active = true;

    @Column(name = "terms_reviewed", nullable = false)
    private boolean termsReviewed = false;

    @Column(name = "terms_reviewed_at")
    private Instant termsReviewedAt;

    @Column(name = "terms_note")
    private String termsNote;

    @Column(name = "robots_respect", nullable = false)
    private boolean robotsRespect = true;

    @Column(name = "last_fetched_at")
    private Instant lastFetchedAt;

    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private Instant createdAt; // DB default now()

    protected SourceEntity() {} // JPA 用

    public SourceEntity(String name, String url, FetchType fetchType) {
        this.name = name;
        this.url = url;
        this.fetchType = fetchType;
    }

    /**
     * 規約確認フラグを設定する。true にした瞬間の時刻を確認日として記録する（SC-06・監査目的）。
     * false に戻したら確認日はクリア（未確認＝収集対象外に戻す）。
     */
    public void setTermsReviewed(boolean reviewed) {
        this.termsReviewed = reviewed;
        this.termsReviewedAt = reviewed ? Instant.now() : null;
    }

    public Long getId() { return id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getUrl() { return url; }
    public void setUrl(String url) { this.url = url; }
    public FetchType getFetchType() { return fetchType; }
    public void setFetchType(FetchType fetchType) { this.fetchType = fetchType; }
    public boolean isActive() { return active; }
    public void setActive(boolean active) { this.active = active; }
    public boolean isTermsReviewed() { return termsReviewed; }
    public Instant getTermsReviewedAt() { return termsReviewedAt; }
    public String getTermsNote() { return termsNote; }
    public void setTermsNote(String termsNote) { this.termsNote = termsNote; }
    public boolean isRobotsRespect() { return robotsRespect; }
    public void setRobotsRespect(boolean robotsRespect) { this.robotsRespect = robotsRespect; }
    public Instant getLastFetchedAt() { return lastFetchedAt; }
    public void setLastFetchedAt(Instant t) { this.lastFetchedAt = t; }
}
