-- V1__init.sql — 初期スキーマ（基本設計 テーブル定義書 準拠・全14テーブル）
-- 日時は timestamptz（UTC 保存・NFR-08）。列挙値は smallint コード値（DD-DAO-09）。
-- 命名は snake_case、制約名は pk_/fk_/uq_/ix_ 接頭辞。

-- pg_trgm（タイトル・要約の部分一致検索用・FR-04-03）
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============ マスタ／利用者データ ============

CREATE TABLE users (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name     text        NOT NULL,
    role             smallint    NOT NULL DEFAULT 1,            -- UserRole 1:User / 9:Admin
    admin_pin_hash   text,                                     -- 管理者の4桁PINのBCryptハッシュ（admin行のみ）
    line_user_id     text,
    notify_enabled   boolean     NOT NULL DEFAULT true,
    last_notified_at timestamptz,
    created_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_line_user_id UNIQUE (line_user_id)
);

CREATE TABLE themes (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    keyword    text        NOT NULL,
    is_active  boolean     NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_themes_user_keyword UNIQUE (user_id, keyword)
);
CREATE INDEX ix_themes_user_id ON themes(user_id);

CREATE TABLE theme_categories (
    theme_id bigint   NOT NULL REFERENCES themes(id) ON DELETE CASCADE,
    category smallint NOT NULL,                                -- Category
    CONSTRAINT pk_theme_categories PRIMARY KEY (theme_id, category)
);

CREATE TABLE sources (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              text        NOT NULL,
    url               text        NOT NULL,
    fetch_type        smallint    NOT NULL,                    -- FetchType 1:Rss/2:HtmlParser/3:Llm
    is_active         boolean     NOT NULL DEFAULT true,
    terms_reviewed    boolean     NOT NULL DEFAULT false,      -- 規約ゲート（false は収集対象外）
    terms_reviewed_at timestamptz,
    terms_note        text,
    robots_respect    boolean     NOT NULL DEFAULT true,
    last_fetched_at   timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now()
);

-- ============ 収集データ（本体） ============

CREATE TABLE articles (
    id                   bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id            bigint      NOT NULL REFERENCES sources(id) ON DELETE RESTRICT,
    title                text        NOT NULL,
    category             smallint    NOT NULL,                 -- Category
    event_date           date,                                 -- 代表日（並び替え・期間フィルタ）
    event_date_text      text,                                 -- 原文（「9月上旬」等）
    event_date_precision smallint    NOT NULL DEFAULT 9,       -- EventDatePrecision
    event_date_kind      smallint    NOT NULL DEFAULT 9,       -- EventDateKind
    location             text,
    url                  text        NOT NULL,
    url_hash             text        NOT NULL,                 -- 正規化URLのハッシュ（冪等の一次担保）
    summary              text,                                 -- 自作要約（本文は保存しない）
    group_key            text,                                 -- 類似グルーピング
    created_at           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_articles_url_hash UNIQUE (url_hash)
);
CREATE INDEX ix_articles_event_date ON articles(event_date);
CREATE INDEX ix_articles_created_at ON articles(created_at);
CREATE INDEX ix_articles_source_id  ON articles(source_id);
CREATE INDEX ix_articles_category   ON articles(category);
-- タイムライン整列キー（FR-04-01・NFR-04）: event_date が NULL なら収集日で代理。
-- ※timestamptz::date はセッションTZ依存で index 式に使えない（IMMUTABLE でない）ため、
--   固定ゾーン(UTC)へ変換してから date 化する（AT TIME ZONE 'UTC' は immutable）。
--   一覧クエリの ORDER BY も同一式を用いること（DD-DAO / 実装Phase0で確定）。
CREATE INDEX ix_articles_timeline
    ON articles ((COALESCE(event_date, (created_at AT TIME ZONE 'UTC')::date)));
-- pg_trgm 部分一致（FR-04-03）
CREATE INDEX gin_articles_title_trgm   ON articles USING gin (title   gin_trgm_ops);
CREATE INDEX gin_articles_summary_trgm ON articles USING gin (summary gin_trgm_ops);

CREATE TABLE article_theme_matches (
    article_id bigint      NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    theme_id   bigint      NOT NULL REFERENCES themes(id)   ON DELETE CASCADE,
    matched_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_article_theme_matches PRIMARY KEY (article_id, theme_id)
);
CREATE INDEX ix_atm_theme_id ON article_theme_matches(theme_id);

-- ============ 利用者×記事／対象 の関連 ============

CREATE TABLE favorite_themes (
    user_id        bigint      NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    theme_id       bigint      NOT NULL REFERENCES themes(id) ON DELETE CASCADE,
    notify_enabled boolean     NOT NULL DEFAULT true,
    created_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_favorite_themes PRIMARY KEY (user_id, theme_id)
);

CREATE TABLE favorite_sources (
    user_id        bigint      NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
    source_id      bigint      NOT NULL REFERENCES sources(id) ON DELETE RESTRICT,
    notify_enabled boolean     NOT NULL DEFAULT true,
    created_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_favorite_sources PRIMARY KEY (user_id, source_id)
);

CREATE TABLE bookmarks (
    user_id    bigint      NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    article_id bigint      NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_bookmarks PRIMARY KEY (user_id, article_id)
);

CREATE TABLE read_states (
    user_id    bigint      NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    article_id bigint      NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    read_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_read_states PRIMARY KEY (user_id, article_id)
);

CREATE TABLE article_notifications (
    user_id     bigint      NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    article_id  bigint      NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    notified_at timestamptz NOT NULL DEFAULT now(),
    result      smallint    NOT NULL DEFAULT 0,               -- 0:Delivered / 1:GaveUp
    CONSTRAINT pk_article_notifications PRIMARY KEY (user_id, article_id)
);

-- ============ ログ／実績 ============

CREATE TABLE notification_logs (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sent_at       timestamptz NOT NULL DEFAULT now(),
    article_count int         NOT NULL,
    message_count int         NOT NULL,                        -- 消費通数（送信先×吹き出し数）
    status        smallint    NOT NULL                         -- NotifyStatus
);
CREATE INDEX ix_notification_logs_sent_at ON notification_logs(sent_at);

CREATE TABLE crawl_logs (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id      bigint      NOT NULL REFERENCES sources(id) ON DELETE RESTRICT,
    started_at     timestamptz NOT NULL DEFAULT now(),
    finished_at    timestamptz,
    item_count     int         NOT NULL DEFAULT 0,
    new_item_count int         NOT NULL DEFAULT 0,
    status         smallint    NOT NULL,                        -- CrawlStatus
    error_message  text
);
CREATE INDEX ix_crawl_logs_started_at ON crawl_logs(started_at);

CREATE TABLE llm_usage_logs (
    id                 bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    called_at          timestamptz  NOT NULL DEFAULT now(),
    model              varchar(100) NOT NULL,
    input_tokens       int          NOT NULL DEFAULT 0,
    output_tokens      int          NOT NULL DEFAULT 0,
    est_cost_micro_jpy bigint       NOT NULL DEFAULT 0,         -- マイクロ円（円×100万・丸め誤差回避）
    crawl_log_id       bigint       REFERENCES crawl_logs(id) ON DELETE SET NULL,
    status             smallint     NOT NULL                    -- LlmCallStatus
);
CREATE INDEX ix_llm_usage_logs_called_at ON llm_usage_logs(called_at);
